	<!-- sfe-backend-core/templates/sfe_head.phtml -->
	<!-- 
		template: {{ thisRoute.tmpl }}
		client_id: {{ thisRoute.client_id }}
		uri: {{ thisRoute.uri }}
	--->
	<head>
		<meta charset="utf-8">
		<meta name="generator" content="SFE 0.1" />
	
{% for css in assets.sfe.css %}
	<link href="{{ css }}" rel="stylesheet" type="text/css">
{% endfor %}
{% for js in assets.sfe.js %}
		<script src="{{ js }}"></script>
{% endfor %}
{% for css in assets.client.css %}
		<link href="{{ css }}" rel="stylesheet" type="text/css">
{% endfor %}
{% for js in assets.client.js %}
		<script src="{{ js }}"></script>
{% endfor %}


{{ '{{' }} include("head.phtml") {{ '}}' }}

	</head>
	<!-- /sfe-backend-core/templates/sfe_head.phtml -->
